[tool.poetry]
name = "llm-football-simulation-engine"
version = "0.1.0"
description = ""
authors = ["cemrtkn <cemrtkn@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
